BEGIN TRANSACTION;
DROP TABLE IF EXISTS "USERS";

CREATE TABLE IF NOT EXISTS "USERS" (
	"id"	INTEGER NOT NULL,
	"acronym"	VARCHAR(5) DEFAULT NULL,
	"password"	VARCHAR(256) NOT NULL DEFAULT '0',
	"cityId"	INTEGER NOT NULL DEFAULT 0,
	"monArr"	INTEGER NOT NULL DEFAULT 0,
	"monDep"	INTEGER NOT NULL DEFAULT 0,
	"tueArr"	INTEGER NOT NULL DEFAULT 0,
	"tueDep"	INTEGER NOT NULL DEFAULT 0,
	"wedArr"	INTEGER NOT NULL DEFAULT 0,
	"wedDep"	INTEGER NOT NULL DEFAULT 0,
	"thuArr"	INTEGER NOT NULL DEFAULT 0,
	"thuDep"	INTEGER NOT NULL DEFAULT 0,
	"friArr"	INTEGER NOT NULL DEFAULT 0,
	"friDep"	INTEGER NOT NULL DEFAULT 0,
	
	FOREIGN KEY(cityId) REFERENCES PERIODS(id),

	FOREIGN KEY(monArr) REFERENCES PERIODS(id),
	FOREIGN KEY(monDep) REFERENCES PERIODS(id),
	FOREIGN KEY(tueArr) REFERENCES PERIODS(id),
	FOREIGN KEY(tueDep) REFERENCES PERIODS(id),
	FOREIGN KEY(wedArr) REFERENCES PERIODS(id),
	FOREIGN KEY(wedDep) REFERENCES PERIODS(id),
	FOREIGN KEY(thuArr) REFERENCES PERIODS(id),
	FOREIGN KEY(thuDep) REFERENCES PERIODS(id),
	FOREIGN KEY(friArr) REFERENCES PERIODS(id),
	FOREIGN KEY(friDep) REFERENCES PERIODS(id),
	
	PRIMARY KEY("id")
);
DROP TABLE IF EXISTS "CITIES";
CREATE TABLE IF NOT EXISTS "CITIES" (
	"id"	INTEGER NOT NULL,
	"name"	VARCHAR(50) NOT NULL DEFAULT '',
	PRIMARY KEY("id")
);
DROP TABLE IF EXISTS "EDT";
CREATE TABLE IF NOT EXISTS "EDT" (
	"id"	INTEGER NOT NULL,
	"acronym"	VARCHAR(5) NOT NULL DEFAULT '',
	"monArr"	INTEGER NOT NULL DEFAULT 0,
	"monDep"	INTEGER NOT NULL DEFAULT 0,
	"tueArr"	INTEGER NOT NULL DEFAULT 0,
	"tueDep"	INTEGER NOT NULL DEFAULT 0,
	"wedArr"	INTEGER NOT NULL DEFAULT 0,
	"wedDep"	INTEGER NOT NULL DEFAULT 0,
	"thuArr"	INTEGER NOT NULL DEFAULT 0,
	"thuDep"	INTEGER NOT NULL DEFAULT 0,
	"friArr"	INTEGER NOT NULL DEFAULT 0,
	"friDep"	INTEGER NOT NULL DEFAULT 0,
	
	FOREIGN KEY(monArr) REFERENCES PERIODS(id),
	FOREIGN KEY(monDep) REFERENCES PERIODS(id),
	FOREIGN KEY(tueArr) REFERENCES PERIODS(id),
	FOREIGN KEY(tueDep) REFERENCES PERIODS(id),
	FOREIGN KEY(wedArr) REFERENCES PERIODS(id),
	FOREIGN KEY(wedDep) REFERENCES PERIODS(id),
	FOREIGN KEY(thuArr) REFERENCES PERIODS(id),
	FOREIGN KEY(thuDep) REFERENCES PERIODS(id),
	FOREIGN KEY(friArr) REFERENCES PERIODS(id),
	FOREIGN KEY(friDep) REFERENCES PERIODS(id),
	
	PRIMARY KEY("id")
);
DROP TABLE IF EXISTS "CARS";
CREATE TABLE IF NOT EXISTS "CARS" (
	"id"	INTEGER NOT NULL,
	"size"	INTEGER NOT NULL,
	"driverId"	INTEGER NOT NULL,
	
	FOREIGN KEY(driverId) REFERENCES USERS(id),
	
	PRIMARY KEY("id")
);
DROP TABLE IF EXISTS "TRAVELS";
CREATE TABLE IF NOT EXISTS "TRAVELS" (
	"id"	INTEGER NOT NULL,
	"dayId"	INTEGER NOT NULL DEFAULT 0,
	"directionId"	INTEGER NOT NULL DEFAULT 0,
	"carId"	INTEGER NOT NULL DEFAULT 0,
	
	FOREIGN KEY(dayId) REFERENCES DAYS(id),
	FOREIGN KEY(directionId) REFERENCES DIRECTIONS(id),
	FOREIGN KEY(carId) REFERENCES CARS(id),
	
	PRIMARY KEY("id")
);
DROP TABLE IF EXISTS "DIRECTIONS";
CREATE TABLE IF NOT EXISTS "DIRECTIONS" (
	"id"	INTEGER NOT NULL,
	"name"	VARCHAR(50) NOT NULL DEFAULT '',
	PRIMARY KEY("id")
);
DROP TABLE IF EXISTS "DAYS";
CREATE TABLE IF NOT EXISTS "DAYS" (
	"id"	INTEGER NOT NULL,
	"name"	VARCHAR(50) NOT NULL DEFAULT '',
	PRIMARY KEY("id")
);
DROP TABLE IF EXISTS "PASSENGERS";
CREATE TABLE IF NOT EXISTS "PASSENGERS" (
	"id"	INTEGER NOT NULL,
	"userId"	INTEGER NOT NULL,
	"travelId"	INTEGER NOT NULL,
	
	FOREIGN KEY(userId) REFERENCES USERS(id),
	FOREIGN KEY(travelId) REFERENCES TRAVELS(id),
	
	PRIMARY KEY("id")
);
DROP TABLE IF EXISTS "PERIODS";
CREATE TABLE IF NOT EXISTS "PERIODS" (
	"id"	INTEGER NOT NULL,
	"hour"	VARCHAR(50) NOT NULL DEFAULT '',
	PRIMARY KEY("id")
);
COMMIT;
